# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.azure_storage_connector import AzureStorageConnector  # noqa: E501
from swagger_client.rest import ApiException


class TestAzureStorageConnector(unittest.TestCase):
    """AzureStorageConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureStorageConnector(self):
        """Test AzureStorageConnector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.azure_storage_connector.AzureStorageConnector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
