# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.postgres_sql_connector import PostgresSqlConnector  # noqa: E501
from swagger_client.rest import ApiException


class TestPostgresSqlConnector(unittest.TestCase):
    """PostgresSqlConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostgresSqlConnector(self):
        """Test PostgresSqlConnector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.postgres_sql_connector.PostgresSqlConnector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
