# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delivery_table_id import DeliveryTableId  # noqa: E501
from swagger_client.rest import ApiException


class TestDeliveryTableId(unittest.TestCase):
    """DeliveryTableId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeliveryTableId(self):
        """Test DeliveryTableId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delivery_table_id.DeliveryTableId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
