# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.custom_string_mock_data import CustomStringMockData  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomStringMockData(unittest.TestCase):
    """CustomStringMockData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomStringMockData(self):
        """Test CustomStringMockData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.custom_string_mock_data.CustomStringMockData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
