# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ms_sql_connector import MsSqlConnector  # noqa: E501
from swagger_client.rest import ApiException


class TestMsSqlConnector(unittest.TestCase):
    """MsSqlConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMsSqlConnector(self):
        """Test MsSqlConnector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ms_sql_connector.MsSqlConnector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
