# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.person_mock_data import PersonMockData  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonMockData(unittest.TestCase):
    """PersonMockData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonMockData(self):
        """Test PersonMockData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.person_mock_data.PersonMockData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
