# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delivery_api import DeliveryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeliveryApi(unittest.TestCase):
    """DeliveryApi unit test stubs"""

    def setUp(self):
        self.api = DeliveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_delivery(self):
        """Test case for create_delivery

        Creates a new delivery  # noqa: E501
        """
        pass

    def test_get_deliveries(self):
        """Test case for get_deliveries

        List deliveries of synth data  # noqa: E501
        """
        pass

    def test_get_delivery_by_id(self):
        """Test case for get_delivery_by_id

        Read a delivery  # noqa: E501
        """
        pass

    def test_get_delivery_progress(self):
        """Test case for get_delivery_progress

        Read the delivery progress.  # noqa: E501
        """
        pass

    def test_start_delivery(self):
        """Test case for start_delivery

        Starts the delivery of the generator  # noqa: E501
        """
        pass

    def test_stop_delivery(self):
        """Test case for stop_delivery

        Stops the delivery of the generator  # noqa: E501
        """
        pass

    def test_update_delivery(self):
        """Test case for update_delivery

        Updates a delivery  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
