# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.qa_report_api import QAReportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQAReportApi(unittest.TestCase):
    """QAReportApi unit test stubs"""

    def setUp(self):
        self.api = QAReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_data_qa_report(self):
        """Test case for download_data_qa_report

        Downloads a QA report of the trained model as .zip file  # noqa: E501
        """
        pass

    def test_download_model_qa_report(self):
        """Test case for download_model_qa_report

        Downloads a QA report of the trained model as .zip file  # noqa: E501
        """
        pass

    def test_get_data_qa_report(self):
        """Test case for get_data_qa_report

        Read a QA report of the trained model  # noqa: E501
        """
        pass

    def test_get_model_qa_report(self):
        """Test case for get_model_qa_report

        Read a QA report of the trained model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
