# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.source_relationship_id import SourceRelationshipId  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceRelationshipId(unittest.TestCase):
    """SourceRelationshipId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceRelationshipId(self):
        """Test SourceRelationshipId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.source_relationship_id.SourceRelationshipId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
