# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.address_mock_data import AddressMockData  # noqa: E501
from swagger_client.rest import ApiException


class TestAddressMockData(unittest.TestCase):
    """AddressMockData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressMockData(self):
        """Test AddressMockData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.address_mock_data.AddressMockData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
