site_name: "mostlyai"
site_url: "https://mostly-ai.github.io/mostlyai-client/"
repo_url: "https://github.com/mostly-ai/mostlyai-client"
repo_name: "mostly-ai/mostlyai-client"

theme:
  name: material
  logo: logo.png
  favicon: favicon.png
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"

  features:
    - navigation.instant
    - navigation.instant.prefetch
#    - navigation.tabs
#    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - toc.follow

  icon:
    repo: fontawesome/brands/github
nav:
  - Home:
    - Index: index.md
  - API Reference:
    - API: api_reference/api.md
    - Model: api_reference/model.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

#markdown_extensions:
#  - pymdownx.blocks.admonition
#  - pymdownx.blocks.details
#  - pymdownx.magiclink
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - pymdownx.snippets:
#      base_path: [!relative $config_dir]
#      check_paths: true
#  - toc:
#      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_root_heading: true
            show_docstring: true
            show_source: false
            show_signature: true
            separate_signature: true
            show_docstring_examples: true
            docstring_section_style: table
            extensions:
            - griffe_fieldz
            docstring_style: google
#
#plugins:
#  - search
#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [mostlyai]
#          options:
#            docstring_style: sphinx
#            show_bases: false
#            show_symbol_type_heading: true
#            show_docstring_examples: true
#            filters: ["!^_"]
#            members_order: source
#            separate_signature: true
#            show_signature_annotations: true
#            signature_crossrefs: true
#            show_symbol_type_toc: true
#            show_root_toc_entry: false
#          rendering:
#            show_source: true
#            show_if_no_docstring: false
