# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseDelivery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'DeliveryId',
        'metadata': 'Metadata',
        'name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'metadata': 'metadata',
        'name': 'name',
        'description': 'description'
    }

    def __init__(self, id=None, metadata=None, name=None, description=None):  # noqa: E501
        """BaseDelivery - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._metadata = None
        self._name = None
        self._description = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if metadata is not None:
            self.metadata = metadata
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this BaseDelivery.  # noqa: E501


        :return: The id of this BaseDelivery.  # noqa: E501
        :rtype: DeliveryId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BaseDelivery.


        :param id: The id of this BaseDelivery.  # noqa: E501
        :type: DeliveryId
        """

        self._id = id

    @property
    def metadata(self):
        """Gets the metadata of this BaseDelivery.  # noqa: E501


        :return: The metadata of this BaseDelivery.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this BaseDelivery.


        :param metadata: The metadata of this BaseDelivery.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    @property
    def name(self):
        """Gets the name of this BaseDelivery.  # noqa: E501


        :return: The name of this BaseDelivery.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BaseDelivery.


        :param name: The name of this BaseDelivery.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this BaseDelivery.  # noqa: E501


        :return: The description of this BaseDelivery.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BaseDelivery.


        :param description: The description of this BaseDelivery.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseDelivery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseDelivery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
