# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseConnector(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'ConnectorId',
        'metadata': 'Metadata',
        'type': 'str',
        'name': 'str',
        'access_type': 'AccessType'
    }

    attribute_map = {
        'id': 'id',
        'metadata': 'metadata',
        'type': 'type',
        'name': 'name',
        'access_type': 'accessType'
    }

    discriminator_value_class_map = {
          'MsSqlConnector': 'MsSqlConnector',
'MySqlConnector': 'MySqlConnector',
'MariaDbConnector': 'MariaDbConnector',
'LocalConnector': 'LocalConnector',
'GoogleCloudStorageConnector': 'GoogleCloudStorageConnector',
'AwsS3StorageConnector': 'AwsS3StorageConnector',
'SnowflakeConnector': 'SnowflakeConnector',
'BigQueryConnector': 'BigQueryConnector',
'AzureStorageConnector': 'AzureStorageConnector',
'DatabricksConnector': 'DatabricksConnector',
'PostgresSqlConnector': 'PostgresSqlConnector',
'OracleConnector': 'OracleConnector'    }

    def __init__(self, id=None, metadata=None, type=None, name=None, access_type=None):  # noqa: E501
        """BaseConnector - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._metadata = None
        self._type = None
        self._name = None
        self._access_type = None
        self.discriminator = 'type'
        if id is not None:
            self.id = id
        if metadata is not None:
            self.metadata = metadata
        self.type = type
        self.name = name
        self.access_type = access_type

    @property
    def id(self):
        """Gets the id of this BaseConnector.  # noqa: E501


        :return: The id of this BaseConnector.  # noqa: E501
        :rtype: ConnectorId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BaseConnector.


        :param id: The id of this BaseConnector.  # noqa: E501
        :type: ConnectorId
        """

        self._id = id

    @property
    def metadata(self):
        """Gets the metadata of this BaseConnector.  # noqa: E501


        :return: The metadata of this BaseConnector.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this BaseConnector.


        :param metadata: The metadata of this BaseConnector.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    @property
    def type(self):
        """Gets the type of this BaseConnector.  # noqa: E501


        :return: The type of this BaseConnector.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BaseConnector.


        :param type: The type of this BaseConnector.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this BaseConnector.  # noqa: E501


        :return: The name of this BaseConnector.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BaseConnector.


        :param name: The name of this BaseConnector.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def access_type(self):
        """Gets the access_type of this BaseConnector.  # noqa: E501


        :return: The access_type of this BaseConnector.  # noqa: E501
        :rtype: AccessType
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type):
        """Sets the access_type of this BaseConnector.


        :param access_type: The access_type of this BaseConnector.  # noqa: E501
        :type: AccessType
        """
        if access_type is None:
            raise ValueError("Invalid value for `access_type`, must not be `None`")  # noqa: E501

        self._access_type = access_type

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseConnector, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseConnector):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
