# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseGenerator(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'GeneratorId',
        'metadata': 'Metadata',
        'name': 'str',
        'tags': 'list[str]',
        'status': 'GeneratorStatus'
    }

    attribute_map = {
        'id': 'id',
        'metadata': 'metadata',
        'name': 'name',
        'tags': 'tags',
        'status': 'status'
    }

    def __init__(self, id=None, metadata=None, name=None, tags=None, status=None):  # noqa: E501
        """BaseGenerator - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._metadata = None
        self._name = None
        self._tags = None
        self._status = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if metadata is not None:
            self.metadata = metadata
        if name is not None:
            self.name = name
        if tags is not None:
            self.tags = tags
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this BaseGenerator.  # noqa: E501


        :return: The id of this BaseGenerator.  # noqa: E501
        :rtype: GeneratorId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BaseGenerator.


        :param id: The id of this BaseGenerator.  # noqa: E501
        :type: GeneratorId
        """

        self._id = id

    @property
    def metadata(self):
        """Gets the metadata of this BaseGenerator.  # noqa: E501


        :return: The metadata of this BaseGenerator.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this BaseGenerator.


        :param metadata: The metadata of this BaseGenerator.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    @property
    def name(self):
        """Gets the name of this BaseGenerator.  # noqa: E501


        :return: The name of this BaseGenerator.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BaseGenerator.


        :param name: The name of this BaseGenerator.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tags(self):
        """Gets the tags of this BaseGenerator.  # noqa: E501


        :return: The tags of this BaseGenerator.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this BaseGenerator.


        :param tags: The tags of this BaseGenerator.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def status(self):
        """Gets the status of this BaseGenerator.  # noqa: E501


        :return: The status of this BaseGenerator.  # noqa: E501
        :rtype: GeneratorStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BaseGenerator.


        :param status: The status of this BaseGenerator.  # noqa: E501
        :type: GeneratorStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseGenerator, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseGenerator):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
