# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Connector(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    discriminator_value_class_map = {
            'MySqlConnector'.lower(): '#/components/schemas/MySqlConnector',
            'PostgresSqlConnector'.lower(): '#/components/schemas/PostgresSqlConnector',
            'MsSqlConnector'.lower(): '#/components/schemas/MsSqlConnector',
            'OracleConnector'.lower(): '#/components/schemas/OracleConnector',
            'MariaDbConnector'.lower(): '#/components/schemas/MariaDbConnector',
            'SnowflakeConnector'.lower(): '#/components/schemas/SnowflakeConnector',
            'BigQueryConnector'.lower(): '#/components/schemas/BigQueryConnector',
            'DatabricksConnector'.lower(): '#/components/schemas/DatabricksConnector',
            'AzureStorageConnector'.lower(): '#/components/schemas/AzureStorageConnector',
            'GoogleCloudStorageConnector'.lower(): '#/components/schemas/GoogleCloudStorageConnector',
            'AwsS3StorageConnector'.lower(): '#/components/schemas/AwsS3StorageConnector',
            'LocalConnector'.lower(): '#/components/schemas/LocalConnector',
    }

    def __init__(self):  # noqa: E501
        """Connector - a model defined in Swagger"""  # noqa: E501
        self.discriminator = 'type'

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Connector, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Connector):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
