# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomStringMockData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'string_pattern': 'str',
        'character_range': 'str'
    }

    attribute_map = {
        'string_pattern': 'stringPattern',
        'character_range': 'characterRange'
    }

    def __init__(self, string_pattern=None, character_range=None):  # noqa: E501
        """CustomStringMockData - a model defined in Swagger"""  # noqa: E501
        self._string_pattern = None
        self._character_range = None
        self.discriminator = None
        if string_pattern is not None:
            self.string_pattern = string_pattern
        if character_range is not None:
            self.character_range = character_range

    @property
    def string_pattern(self):
        """Gets the string_pattern of this CustomStringMockData.  # noqa: E501


        :return: The string_pattern of this CustomStringMockData.  # noqa: E501
        :rtype: str
        """
        return self._string_pattern

    @string_pattern.setter
    def string_pattern(self, string_pattern):
        """Sets the string_pattern of this CustomStringMockData.


        :param string_pattern: The string_pattern of this CustomStringMockData.  # noqa: E501
        :type: str
        """

        self._string_pattern = string_pattern

    @property
    def character_range(self):
        """Gets the character_range of this CustomStringMockData.  # noqa: E501


        :return: The character_range of this CustomStringMockData.  # noqa: E501
        :rtype: str
        """
        return self._character_range

    @character_range.setter
    def character_range(self, character_range):
        """Sets the character_range of this CustomStringMockData.


        :param character_range: The character_range of this CustomStringMockData.  # noqa: E501
        :type: str
        """

        self._character_range = character_range

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomStringMockData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomStringMockData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
