# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryTable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'DeliveryTableId',
        'synthetic_table_id': 'SyntheticTableId',
        'destination': 'ConnectorId',
        'location': 'str'
    }

    attribute_map = {
        'id': 'id',
        'synthetic_table_id': 'syntheticTableId',
        'destination': 'destination',
        'location': 'location'
    }

    def __init__(self, id=None, synthetic_table_id=None, destination=None, location=None):  # noqa: E501
        """DeliveryTable - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._synthetic_table_id = None
        self._destination = None
        self._location = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if synthetic_table_id is not None:
            self.synthetic_table_id = synthetic_table_id
        if destination is not None:
            self.destination = destination
        if location is not None:
            self.location = location

    @property
    def id(self):
        """Gets the id of this DeliveryTable.  # noqa: E501


        :return: The id of this DeliveryTable.  # noqa: E501
        :rtype: DeliveryTableId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeliveryTable.


        :param id: The id of this DeliveryTable.  # noqa: E501
        :type: DeliveryTableId
        """

        self._id = id

    @property
    def synthetic_table_id(self):
        """Gets the synthetic_table_id of this DeliveryTable.  # noqa: E501


        :return: The synthetic_table_id of this DeliveryTable.  # noqa: E501
        :rtype: SyntheticTableId
        """
        return self._synthetic_table_id

    @synthetic_table_id.setter
    def synthetic_table_id(self, synthetic_table_id):
        """Sets the synthetic_table_id of this DeliveryTable.


        :param synthetic_table_id: The synthetic_table_id of this DeliveryTable.  # noqa: E501
        :type: SyntheticTableId
        """

        self._synthetic_table_id = synthetic_table_id

    @property
    def destination(self):
        """Gets the destination of this DeliveryTable.  # noqa: E501


        :return: The destination of this DeliveryTable.  # noqa: E501
        :rtype: ConnectorId
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this DeliveryTable.


        :param destination: The destination of this DeliveryTable.  # noqa: E501
        :type: ConnectorId
        """

        self._destination = destination

    @property
    def location(self):
        """Gets the location of this DeliveryTable.  # noqa: E501

        schema.table or path configuration (depending on the type of connector)  # noqa: E501

        :return: The location of this DeliveryTable.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this DeliveryTable.

        schema.table or path configuration (depending on the type of connector)  # noqa: E501

        :param location: The location of this DeliveryTable.  # noqa: E501
        :type: str
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryTable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryTable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
