# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Figures(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_figures': 'int',
        'figures': 'Figure'
    }

    attribute_map = {
        'total_figures': 'totalFigures',
        'figures': 'figures'
    }

    def __init__(self, total_figures=None, figures=None):  # noqa: E501
        """Figures - a model defined in Swagger"""  # noqa: E501
        self._total_figures = None
        self._figures = None
        self.discriminator = None
        if total_figures is not None:
            self.total_figures = total_figures
        if figures is not None:
            self.figures = figures

    @property
    def total_figures(self):
        """Gets the total_figures of this Figures.  # noqa: E501


        :return: The total_figures of this Figures.  # noqa: E501
        :rtype: int
        """
        return self._total_figures

    @total_figures.setter
    def total_figures(self, total_figures):
        """Sets the total_figures of this Figures.


        :param total_figures: The total_figures of this Figures.  # noqa: E501
        :type: int
        """

        self._total_figures = total_figures

    @property
    def figures(self):
        """Gets the figures of this Figures.  # noqa: E501


        :return: The figures of this Figures.  # noqa: E501
        :rtype: Figure
        """
        return self._figures

    @figures.setter
    def figures(self, figures):
        """Sets the figures of this Figures.


        :param figures: The figures of this Figures.  # noqa: E501
        :type: Figure
        """

        self._figures = figures

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Figures, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Figures):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
