# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.page import Page  # noqa: F401,E501

class InlineResponse2002(Page):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'results': 'list[BaseSyntheticData]'
    }
    if hasattr(Page, "swagger_types"):
        swagger_types.update(Page.swagger_types)

    attribute_map = {
        'results': 'results'
    }
    if hasattr(Page, "attribute_map"):
        attribute_map.update(Page.attribute_map)

    def __init__(self, results=None, *args, **kwargs):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger"""  # noqa: E501
        self._results = None
        self.discriminator = None
        if results is not None:
            self.results = results
        Page.__init__(self, *args, **kwargs)

    @property
    def results(self):
        """Gets the results of this InlineResponse2002.  # noqa: E501


        :return: The results of this InlineResponse2002.  # noqa: E501
        :rtype: list[BaseSyntheticData]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this InlineResponse2002.


        :param results: The results of this InlineResponse2002.  # noqa: E501
        :type: list[BaseSyntheticData]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
