# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobProgress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_date': 'str',
        'table_progress': 'Progress',
        'logs': 'list[Step]'
    }

    attribute_map = {
        'start_date': 'startDate',
        'table_progress': 'tableProgress',
        'logs': 'logs'
    }

    def __init__(self, start_date=None, table_progress=None, logs=None):  # noqa: E501
        """JobProgress - a model defined in Swagger"""  # noqa: E501
        self._start_date = None
        self._table_progress = None
        self._logs = None
        self.discriminator = None
        if start_date is not None:
            self.start_date = start_date
        if table_progress is not None:
            self.table_progress = table_progress
        if logs is not None:
            self.logs = logs

    @property
    def start_date(self):
        """Gets the start_date of this JobProgress.  # noqa: E501

        Timestamp in UTC 2023‐09‐07T18:40:39Z  # noqa: E501

        :return: The start_date of this JobProgress.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this JobProgress.

        Timestamp in UTC 2023‐09‐07T18:40:39Z  # noqa: E501

        :param start_date: The start_date of this JobProgress.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def table_progress(self):
        """Gets the table_progress of this JobProgress.  # noqa: E501


        :return: The table_progress of this JobProgress.  # noqa: E501
        :rtype: Progress
        """
        return self._table_progress

    @table_progress.setter
    def table_progress(self, table_progress):
        """Sets the table_progress of this JobProgress.


        :param table_progress: The table_progress of this JobProgress.  # noqa: E501
        :type: Progress
        """

        self._table_progress = table_progress

    @property
    def logs(self):
        """Gets the logs of this JobProgress.  # noqa: E501


        :return: The logs of this JobProgress.  # noqa: E501
        :rtype: list[Step]
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """Sets the logs of this JobProgress.


        :param logs: The logs of this JobProgress.  # noqa: E501
        :type: list[Step]
        """

        self._logs = logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobProgress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobProgress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
