# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Metadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'str',
        'owner_id': 'str',
        'owner_name': 'str'
    }

    attribute_map = {
        'created_at': 'createdAt',
        'owner_id': 'ownerId',
        'owner_name': 'ownerName'
    }

    def __init__(self, created_at=None, owner_id=None, owner_name=None):  # noqa: E501
        """Metadata - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._owner_id = None
        self._owner_name = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if owner_id is not None:
            self.owner_id = owner_id
        if owner_name is not None:
            self.owner_name = owner_name

    @property
    def created_at(self):
        """Gets the created_at of this Metadata.  # noqa: E501


        :return: The created_at of this Metadata.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Metadata.


        :param created_at: The created_at of this Metadata.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def owner_id(self):
        """Gets the owner_id of this Metadata.  # noqa: E501


        :return: The owner_id of this Metadata.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this Metadata.


        :param owner_id: The owner_id of this Metadata.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    @property
    def owner_name(self):
        """Gets the owner_name of this Metadata.  # noqa: E501


        :return: The owner_name of this Metadata.  # noqa: E501
        :rtype: str
        """
        return self._owner_name

    @owner_name.setter
    def owner_name(self, owner_name):
        """Sets the owner_name of this Metadata.


        :param owner_name: The owner_name of this Metadata.  # noqa: E501
        :type: str
        """

        self._owner_name = owner_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Metadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Metadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
