# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QASummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accuracy': 'str',
        'univariate': 'str',
        'bivariate': 'str',
        'coherence': 'str'
    }

    attribute_map = {
        'accuracy': 'accuracy',
        'univariate': 'univariate',
        'bivariate': 'bivariate',
        'coherence': 'coherence'
    }

    def __init__(self, accuracy=None, univariate=None, bivariate=None, coherence=None):  # noqa: E501
        """QASummary - a model defined in Swagger"""  # noqa: E501
        self._accuracy = None
        self._univariate = None
        self._bivariate = None
        self._coherence = None
        self.discriminator = None
        if accuracy is not None:
            self.accuracy = accuracy
        if univariate is not None:
            self.univariate = univariate
        if bivariate is not None:
            self.bivariate = bivariate
        if coherence is not None:
            self.coherence = coherence

    @property
    def accuracy(self):
        """Gets the accuracy of this QASummary.  # noqa: E501


        :return: The accuracy of this QASummary.  # noqa: E501
        :rtype: str
        """
        return self._accuracy

    @accuracy.setter
    def accuracy(self, accuracy):
        """Sets the accuracy of this QASummary.


        :param accuracy: The accuracy of this QASummary.  # noqa: E501
        :type: str
        """

        self._accuracy = accuracy

    @property
    def univariate(self):
        """Gets the univariate of this QASummary.  # noqa: E501


        :return: The univariate of this QASummary.  # noqa: E501
        :rtype: str
        """
        return self._univariate

    @univariate.setter
    def univariate(self, univariate):
        """Sets the univariate of this QASummary.


        :param univariate: The univariate of this QASummary.  # noqa: E501
        :type: str
        """

        self._univariate = univariate

    @property
    def bivariate(self):
        """Gets the bivariate of this QASummary.  # noqa: E501


        :return: The bivariate of this QASummary.  # noqa: E501
        :rtype: str
        """
        return self._bivariate

    @bivariate.setter
    def bivariate(self, bivariate):
        """Sets the bivariate of this QASummary.


        :param bivariate: The bivariate of this QASummary.  # noqa: E501
        :type: str
        """

        self._bivariate = bivariate

    @property
    def coherence(self):
        """Gets the coherence of this QASummary.  # noqa: E501

        Only applicable for linked tables.  # noqa: E501

        :return: The coherence of this QASummary.  # noqa: E501
        :rtype: str
        """
        return self._coherence

    @coherence.setter
    def coherence(self, coherence):
        """Sets the coherence of this QASummary.

        Only applicable for linked tables.  # noqa: E501

        :param coherence: The coherence of this QASummary.  # noqa: E501
        :type: str
        """

        self._coherence = coherence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QASummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QASummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
