# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_connector import BaseConnector  # noqa: F401,E501

class SnowflakeConnector(BaseConnector):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account': 'str',
        'username': 'str',
        'password': 'str',
        'warehouse': 'str',
        'database': 'str',
        'schema': 'str'
    }
    if hasattr(BaseConnector, "swagger_types"):
        swagger_types.update(BaseConnector.swagger_types)

    attribute_map = {
        'account': 'account',
        'username': 'username',
        'password': 'password',
        'warehouse': 'warehouse',
        'database': 'database',
        'schema': 'schema'
    }
    if hasattr(BaseConnector, "attribute_map"):
        attribute_map.update(BaseConnector.attribute_map)

    def __init__(self, account=None, username=None, password=None, warehouse=None, database=None, schema=None, *args, **kwargs):  # noqa: E501
        """SnowflakeConnector - a model defined in Swagger"""  # noqa: E501
        self._account = None
        self._username = None
        self._password = None
        self._warehouse = None
        self._database = None
        self._schema = None
        self.discriminator = None
        self.account = account
        self.username = username
        self.password = password
        if warehouse is not None:
            self.warehouse = warehouse
        self.database = database
        if schema is not None:
            self.schema = schema
        BaseConnector.__init__(self, *args, **kwargs)

    @property
    def account(self):
        """Gets the account of this SnowflakeConnector.  # noqa: E501


        :return: The account of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this SnowflakeConnector.


        :param account: The account of this SnowflakeConnector.  # noqa: E501
        :type: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def username(self):
        """Gets the username of this SnowflakeConnector.  # noqa: E501


        :return: The username of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this SnowflakeConnector.


        :param username: The username of this SnowflakeConnector.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this SnowflakeConnector.  # noqa: E501


        :return: The password of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this SnowflakeConnector.


        :param password: The password of this SnowflakeConnector.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def warehouse(self):
        """Gets the warehouse of this SnowflakeConnector.  # noqa: E501


        :return: The warehouse of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._warehouse

    @warehouse.setter
    def warehouse(self, warehouse):
        """Sets the warehouse of this SnowflakeConnector.


        :param warehouse: The warehouse of this SnowflakeConnector.  # noqa: E501
        :type: str
        """

        self._warehouse = warehouse

    @property
    def database(self):
        """Gets the database of this SnowflakeConnector.  # noqa: E501


        :return: The database of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this SnowflakeConnector.


        :param database: The database of this SnowflakeConnector.  # noqa: E501
        :type: str
        """
        if database is None:
            raise ValueError("Invalid value for `database`, must not be `None`")  # noqa: E501

        self._database = database

    @property
    def schema(self):
        """Gets the schema of this SnowflakeConnector.  # noqa: E501


        :return: The schema of this SnowflakeConnector.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this SnowflakeConnector.


        :param schema: The schema of this SnowflakeConnector.  # noqa: E501
        :type: str
        """

        self._schema = schema

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SnowflakeConnector, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnowflakeConnector):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
