# coding: utf-8

"""
    Public API of Mostly AI

    Public API of Mostly AI  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SslSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'root_certificate': 'Certificate',
        'ssl_certificate': 'Certificate',
        'ssl_certificate_key': 'Certificate'
    }

    attribute_map = {
        'root_certificate': 'rootCertificate',
        'ssl_certificate': 'sslCertificate',
        'ssl_certificate_key': 'sslCertificateKey'
    }

    def __init__(self, root_certificate=None, ssl_certificate=None, ssl_certificate_key=None):  # noqa: E501
        """SslSettings - a model defined in Swagger"""  # noqa: E501
        self._root_certificate = None
        self._ssl_certificate = None
        self._ssl_certificate_key = None
        self.discriminator = None
        if root_certificate is not None:
            self.root_certificate = root_certificate
        if ssl_certificate is not None:
            self.ssl_certificate = ssl_certificate
        if ssl_certificate_key is not None:
            self.ssl_certificate_key = ssl_certificate_key

    @property
    def root_certificate(self):
        """Gets the root_certificate of this SslSettings.  # noqa: E501


        :return: The root_certificate of this SslSettings.  # noqa: E501
        :rtype: Certificate
        """
        return self._root_certificate

    @root_certificate.setter
    def root_certificate(self, root_certificate):
        """Sets the root_certificate of this SslSettings.


        :param root_certificate: The root_certificate of this SslSettings.  # noqa: E501
        :type: Certificate
        """

        self._root_certificate = root_certificate

    @property
    def ssl_certificate(self):
        """Gets the ssl_certificate of this SslSettings.  # noqa: E501


        :return: The ssl_certificate of this SslSettings.  # noqa: E501
        :rtype: Certificate
        """
        return self._ssl_certificate

    @ssl_certificate.setter
    def ssl_certificate(self, ssl_certificate):
        """Sets the ssl_certificate of this SslSettings.


        :param ssl_certificate: The ssl_certificate of this SslSettings.  # noqa: E501
        :type: Certificate
        """

        self._ssl_certificate = ssl_certificate

    @property
    def ssl_certificate_key(self):
        """Gets the ssl_certificate_key of this SslSettings.  # noqa: E501


        :return: The ssl_certificate_key of this SslSettings.  # noqa: E501
        :rtype: Certificate
        """
        return self._ssl_certificate_key

    @ssl_certificate_key.setter
    def ssl_certificate_key(self, ssl_certificate_key):
        """Sets the ssl_certificate_key of this SslSettings.


        :param ssl_certificate_key: The ssl_certificate_key of this SslSettings.  # noqa: E501
        :type: Certificate
        """

        self._ssl_certificate_key = ssl_certificate_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SslSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SslSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
