name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    id: intro
    attributes:
      value: "Thanks for reporting a bug! Please fill out the information below."
  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: The version of Python you're using.
      placeholder: "e.g., 3.8, 3.9, 3.10"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context like OS, environment setup, etc.
